### PR TITLE
Added stage name to API name

### PR DESCRIPTION
**Pull request by Nopik**

### CODE REVIEW

**Comment by doapp-ryanp** [comment]
Isnt the stage already in the API Gateway for the project and in the URL? it is for me...

(APIG Web UI > resources > stages) and then https://UUID.execute-api.us-east-1.amazonaws.com/prod ...

**Comment by Nopik** [comment]
It is not about the URLs. It is about the names. Currently if you have 5 stages in project `foo` and you go to AWS API Gateway console, you see 5 `foo` APIs and you dont know which is which (and each have 1 stage). Surely modifying the JAWS code to create 1 API with 5 stages is the way to go, this is short-term solution to conveniently tell one API from another.

**Comment by doapp-ryanp** [comment]
ah ok gotcha makes sense. @ac360 ok to merge? this is ur area of expertise...

**Comment by ac360** [comment]
:+1:

**Pull request merged**
