### PR TITLE
[feature] api response parameters

### PR DESCRIPTION
**Pull request by icereval**
Corrects display of stage's selection during `jaws dash`, removes duplicate methods and fixed `responseParameters` api gateway option.

awsm.json - e.g. one can now configure CORS
```
  "apiGateway": {
    "deploy": false,
    "cloudFormation": {
      ...
      "ApiKeyRequired": false,
      "RequestTemplates": {},
      "RequestParameters": {},
      "Responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {
            "method.response.header.Access-Control-Allow-Origin": "'*'"
          },
          "responseTemplates": {
            "application/json": ""
          }
        }
...
```

### CODE REVIEW

**Comment by ac360** [comment]
This looks great.  I'll test this tonight.  Thank you @icereval

**Comment by ac360** [comment]
I didn't get to this tonight.  I was held up on some other bugs.  Digging into this tomorrow though.

**Comment by ac360** [comment]
I made one change.  You switched the template mapping for the requestParamers which resulted in API Gateway errors.  Any reason in particular you did this?

**Comment by icereval** [comment]
Sorry for not clarifying, here are the details behind the change.

---

As far as I can tell Amazon's documentation on `method:put` `requestParameters` contradicts itself.

https://docs.aws.amazon.com/apigateway/api-reference/link-relation/method-put/

First it states in the data model definition `requestParameters` if of type `Boolean` which matches that of its sister endpoint `methodresponse:put` `responseParameters`. Reading the definition though `requestParameters` mentions nothing of a Boolean value unlike its counter part and sounds / is identical to the definition of the `integration:put` endpoint.

I tested a few scenarios attempting to populate this field with the following results:

```json
"RequestTemplates": {},
"RequestParameters": {
  "integration.request.header.xyz": "'foo'"
},
```

1. In the original configuration, setting any string value to `requestParameters`, even if static fails with the following error:
> { logref: '4df300a1-61a4-11e5-89eb-fb5236c26d22',
  message: 'Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: \'foo\']',
  statusCode: 400 }

2. Changing the code to feed the key/value pair, I attempted to set the literal values as stated in the definition of `method:put` `requestParameters`, it really seems to want a Boolean which matches `methodresponse:put`.
> { logref: 'fa40d620-61a1-11e5-92ee-ab120241c745',
  message: '\'\'FOO\'\' can not be converted to an Boolean',
  statusCode: 400 }

3. At this point I decided it was likely a good idea to make it match the working `methodresponse:put` `responseParameters`, this at a minimum gives a more appropriate error message where 'integration.request...' is the key.
> { logref: 'cc3d975d-61a3-11e5-9754-c13457616248',
  message: 'Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: integration.request.header.xyz]',
  statusCode: 400 }

In the long run I could not seem to use this feature programmatically via the API or even the web console.

I was however able to accomplish my goal of setting a parameter to a variable input for my lambda function using the `RequestTemplates`. (we should see about not having to string encode the object in a future update :+1:) e.g.

```json
"RequestTemplates": {
  "application/json": "{\"provider\": \"$input.params('provider')\"}"
},
"RequestParameters": {},
```

Let me know if you have any luck, or if I'm overlooking something here.

Michael

**Comment by icereval** [comment]
Well wrote all that for nothing, decided to review in detail the tests and found I was simply formatting the request incorrectly, thanks for catching that.

```json
"RequestTemplates": {},
"RequestParameters": {
  "integration.request.path.provider": "method.request.path.provider"
},
```

**Pull request merged**
