### PR TITLE
#49 Added MySQL, Redis, and Elasticsearch

### PR DESCRIPTION
**Pull request by justinmealey**
I wanted to commit back a rough version of this in order to get feedback as to how you want to structure everything.

In order to test out each service, you'll have to have already setup each individual server (mysql, redis, es) prior to running these, and change the config settings.  I couldn't use your dotenv config maker for most of what I needed, since the configs required integers, arrays, etc.

The MySQL driver will let you designate a master and read slaves, so I put in localhost as both to give you a rough idea of how to configure that.  Although I have `Client.prototype.read_query`'s going to all (`*`), you can make them go to only read slaves by doing something like naming your slaves `SLAVE1` `SLAVE2` and then changing that value to `SLAVE*`.

I also snuck in a part to automatically include all the models, so you don't have to manually add them in `lib/index.js` -- I can make another pull request that will remove the requirement for the file to have `model_` in the beginning since we can assume that everything in `lib/models` is a model.

### CODE REVIEW

**Comment by ac360** [comment]
@justinmealey Awesome stuff here.  I'm going to dig into this tomorrow. 

Could you take a second to check out the [JAWS V1 Specifications](https://docs.google.com/document/d/1SeTgtsQc620vcwgGMZ4F2yuWVf-A3JmpTn1VT8pKYsA/edit?usp=sharing), particularly the **aws-modules** part?  It's how you will be able to package this into a module so that everyone else can install it into their JAWS projects.  Your work is going to be in high demand.

Please let me know if the **aws-modules** system can be improved before we implement it.

Nice work @justinmealey!  Super cool stuff here :beers:

**Comment by justinmealey** [comment]
Awesome -- one thing I didn't get is if you are using npm to be the host for the aws-modules and people are publishing them to npm.  One thing is that we'll want to namespace those modules with `jaws` so they'd be `jaws-lambda-somelambda`, just to prevent any unintentional interference with other people's modules.

When the structure is good to go on the modules side, I'll rewrite each of these clients as modules.

**Comment by ac360** [comment]
@justinmealey We're not going to use `npm` for the `aws-modules`.  The CLI will simply fetch the repo at the URL and transfer the files where they need to go in your current working directory. 

We'll make a tiny module registry somewhere.  We can use JAWS for that.  We can easily make an aws-module search back-end via lambda!!

**Comment by callmeStriking** [comment]
@ac360 it sounds like npm would fit the use case, and it has the added benefit of already existing. It could give you less to think about and less to build if you use it. 

The only thing it doesn't have is multiple language support. Perhaps we could attempt to integrate Maven support as well, for those Java packages. 

But it's easier to reuse code than to reinvent it slightly differently.

**Comment by mcwhittemore** [comment]
What is the state of this PR now that we have the v1.0 specs? It seems like it should be closed to me and then used to help conversations about different database options.

**Comment by doapp-ryanp** [comment]
Closing this with v1 avail now. Topics discussed in this PR would be good candidates for [awsm](https://github.com/awsm-org/awsm) modules.

**Pull request closed without merging**
