### PR TITLE
Fixed module command.

### PR DESCRIPTION
**Pull request by dekz**
Parameters for install and update can be >= 2 (--save, --dont-install etc).

### CODE REVIEW

**Comment by doapp-ryanp** [comment]
Thanks @dekz .  Coincidentally I was working on this fix in another branch already, and did not see this PR until now.  Closing as fixed in https://github.com/jaws-framework/JAWS/pull/142 HOWEVER I still have some todo's in there to better handle params length checking (I have an idea just haven't had time to implement).  Really wish commander had sub-sub-command support :)

**Comment by doapp-ryanp** [comment]
I am gonna steal your [install,update] help syntax tho

**Comment by dekz** [comment]
Hah ok cool. Do you know what the current situation is with the `--save` option, should this be functional now?

**Comment by doapp-ryanp** [comment]
Yep should work, but I have to admit I haven't had time to make a testcase for it.  Here is the entry point for the logic: https://github.com/jaws-framework/JAWS/blob/master/lib/commands/module_install.js#L53

If you run into a problem with it, please open a new issue and I'll dig into it (prob tonight)

**Pull request closed without merging**
