### PR TITLE
V1.0

### PR DESCRIPTION
**Pull request by andrej523**

### CODE REVIEW

**Comment by eahefnawy** [comment]
Woooooooo!!! :dancer: congrats!

**Comment by ac360** [comment]
@eahefnawy You rock for saying that.  We've got a few more days of work needed.  We'll be making progress rapidly this week.  Lots of good stuff coming.

**Comment by eahefnawy** [comment]
awesome! I'm taking a tour around the codebase today, getting ready for some debugging.

**Comment by ac360** [comment]
Thx.  I'm doing some quick fixes before going to bed.  Just a few bugs preventing deploy...

**Pull request merged**
