### PR TITLE
Fix problem with region not being passed for API Gateway deployments

### PR DESCRIPTION
**Pull request by boushley**
Using region directly instead of as an object.

The rest of this file seems to rely on region being a string not an object.
Also a fresh project results in region being a string not object, so lets just use that.

### CODE REVIEW

**Comment by doapp-ryanp** [comment]
Not merging because this exposes an even larger bug.

@ac360 the `CMD` class [where its setting `_this._regions`](https://github.com/jaws-framework/JAWS/blob/master/lib/commands/deploy_endpoint.js#L43) is incorrect.  If `regions` param is not passed, this logic will get all the STAGE objects NOT region names.  More specifically since you are calling `Object.keys()` on an array, its just going to return integer numbers...

I'll let you fix @ac360 because it looks like it is going to require some refactor

**Comment by boushley** [comment]
Might consider merging this for as an interim step since as it stands endpoints are always created in `us-east-1` even though all of the output says it was your provided region (of which `us-west-2` is the only other one that works for publicly available services).

**Comment by ac360** [comment]
Going to revisit this one later.  We are making last minute breaking changes which may affect this.

**Comment by ac360** [comment]
BTW Thanks @boushley!

**Pull request closed without merging**
